### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by aadis** [devopshq/youtrack#1]
Seems like a problem with index.

> $ pip install dohq_youtrack
> Downloading/unpacking dohq-youtrack
>   Could not find a version that satisfies the requirement dohq-youtrack (from versions: 0.0.1.dev15, 0.0.1.dev15)
> Cleaning up...
> No distributions matching the version for dohq-youtrack
> Storing debug log for failure in /home/zoid/.pip/pip.log
> 

But giving full path to tar.gz works. I'm not blocked, but thought I'd let you know. And thanks for the stellar work!

> $ pip install https://pypi.python.org/packages/b8/68/d9c9a267509443516b5b811b0d22de215f152c36eb82cbb12bd09cfa0f77/dohq-youtrack-0.0.1.dev15.tar.gz#md5=df246c7589e83370d898a06088977ce9
> Downloading/unpacking https://pypi.python.org/packages/b8/68/d9c9a267509443516b5b811b0d22de215f152c36eb82cbb12bd09cfa0f77/dohq-youtrack-0.0.1.dev15.tar.gz
>   Downloading dohq-youtrack-0.0.1.dev15.tar.gz
>   Running setup.py (path:/tmp/pip-396b8yr5-build/setup.py) egg_info for package from https://pypi.python.org/packages/b8/68/d9c9a267509443516b5b811b0d22de215f152c36eb82cbb12bd09cfa0f77/dohq-youtrack-0.0.1.dev15.tar.gz
>     /home/zoid/.virtualenvs/zoid/lib/python3.4/site-packages/setuptools/dist.py:331: UserWarning: Normalizing '0.30.0.a0' to '0.30.0a0'
>       normalized_version,
>     no previously-included directories found matching 'wheel/test/*/dist'
>     no previously-included directories found matching 'wheel/test/*/build'
> 
>     Installed /tmp/pip-396b8yr5-build/.eggs/wheel-0.30.0a0-py3.4.egg
> 
> Downloading/unpacking httplib2 (from dohq-youtrack==0.0.1.dev15)
>   Downloading httplib2-0.9.2.zip (210kB): 210kB downloaded
>   Running setup.py (path:/tmp/pip-build-ld137bqu/httplib2/setup.py) egg_info for package httplib2
> 
> Installing collected packages: httplib2, dohq-youtrack
>   Running setup.py install for httplib2
> 
>   Could not find .egg-info directory in install record for httplib2 (from dohq-youtrack==0.0.1.dev15)
>   Running setup.py install for dohq-youtrack
> 
>   Could not find .egg-info directory in install record for dohq-youtrack==0.0.1.dev15 from https://pypi.python.org/packages/b8/68/d9c9a267509443516b5b811b0d22de215f152c36eb82cbb12bd09cfa0f77/dohq-youtrack-0.0.1.dev15.tar.gz
> Successfully installed httplib2 dohq-youtrack
> Cleaning up...
>

**Comment by alkovpro** [comment]
Thanks for reaching us out!
I think you could resolve this problem adding --pre option:
pip install --pre dohq-youtrack

There's some work to do before we can say the module is ready to be 'release' and pip searches only release versions on some systems such as debian.
Sorry for this, I'll try to make release in December.
Best regards,
thanks for giving it a try!
