### ISSUE TITLE
What version of the YouTrack API does your package utilize?

### ISSUE THREAD

**Issue by konstunn** [devopshq/youtrack#23]
What version of the YT API does your package utilize and is it connected somehow to this project https://github.com/JetBrains/youtrack-rest-python-library ?

**Comment by konstunn** [comment]
Ok, I have found out that you use deprecated version of the YouTrack API.

**Comment by SAnCherepan** [comment]
@konstunn, you are correct, this library uses deprecated API.
Originally it was just a Python 3 rework for the [official JetBrains Python 2 library](https://github.com/JetBrains/youtrack-rest-python-library) and we supported it as we could.

We do not have any plans for rewriting it as [JetBrains says](https://github.com/JetBrains/youtrack-rest-python-library#important-deprecation-notice) that they will provide support for both Python 3 and current API by the end of February.

If their library is good enough, we will consider discontinuing support for this one.
