### ISSUE TITLE
get_issues returns a list but all are the same value

### ISSUE THREAD

**Issue by velvel32** [devopshq/youtrack#3]
connection.get_issues returns a list of issues. but all the members of the list are the same item !
since it's python i tried diagnosing this. I added code to get_issues that shows the Issues being created correctly, but when added to a list they all become the same ??
i am guessing that the issue is with the parent object, YouTrackObject. it has a static instance reference to _data = {}. which will apply to all instances of the object. therefore the list has 10 references to the same data. 
see here: http://forums.devshed.com/python-programming-11/appending-object-list-overwrites-previous-842713.html
thanks

[snippets.txt](https://github.com/devopshq/youtrack/files/714675/snippets.txt)

**Comment by alkovpro** [comment]
Thanks for the tip. It's a little more complicated though. I'll try to fix it this weekend.

**Comment by pasaranax** [comment]
Hi. I encountered the same problem. Is there any solution?

**Comment by Tim55667757** [comment]
Sorry, we'll try to fix it soon.

**Comment by domenkozar** [comment]
Yes, the issue is `_data` which is attached to the class. The problem is that attributes are implemented with logs of magic, more than it's really needed so you quickly hit infinite recursion errors.

**Comment by alkovpro** [comment]
@domenkozar Yes - I'm aware of that :) It was a quick attempt to fix horrible code style of the original python 2 version, which was written by someone who haven't heard about PEP8 :)

I think I'll finally get to fix this project in first few days of June 2017 :)

**Comment by alkovpro** [comment]
Fixed
