### ISSUE TITLE
Запрос несуществующего атрибута issue приводит к RuntimeError

### ISSUE THREAD

**Issue by allburov** [devopshq/youtrack#5]
При запросе несуществующего атрибута у issue код входит в рекурсию (https://github.com/devopshq/youtrack/blob/master/youtrack/youtrack.py#L171) и выпадает с ошибкой
```
{RuntimeError}maximum recursion depth exceeded while calling a Python object
```

**Ожидается** - какое-либо исключение, вроде AttributeError

**Comment by alkovpro** [comment]
Fixed
